apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus_uid
  url: http://prometheus:9090
  editable: true
  isDefault: false
  jsonData:
    timeout: 60
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    cacheLevel: High